language: node_js
node_js:
  - "10.15.3"
cache:
  - directories:
    - node_modules

addons:
  ssh_known_hosts:
    - dubell.io

branches:
  only:
    - master

script:
  - "yarn lint:js"
  - "yarn clean"
  - "yarn build"

# Gives us the ssh key
before_deploy:
  - openssl aes-256-cbc -K $encrypted_b75397c6be1b_key -iv $encrypted_b75397c6be1b_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script # put the release on our live site
    skip_cleanup: true
    script:
      - rsync -avzh -e "ssh -p 37300" $TRAVIS_BUILD_DIR/public travis@dubell.io:dubell.io
    on:
      branch: master